#pragma config(Sensor, S1,     my_sensor,      sensorLightActive)
#pragma config(Motor,  motorA,          A,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          C,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1)
	{
			if(SensorValue[my_sensor] <= 18){
			motor[motorA] = 10;
			motor[motorC] = 40;
		}
		else	if(SensorValue[my_sensor] > 19 && SensorValue[my_sensor] < 24){
			motor[motorA] = 20;
			motor[motorC] = 35;
		}
		 else if(SensorValue[my_sensor] > 25 && SensorValue[my_sensor] < 34){
			motor[motorA] = 20;
			motor[motorC] = 30;
		}
		else if(SensorValue[my_sensor] > 35 && SensorValue[my_sensor] < 44){
			motor[motorA] = 30;
			motor[motorC] = 30;
		}
		else if(SensorValue[my_sensor] > 44 && SensorValue[my_sensor] < 54){
			motor[motorA] = 35;
			motor[motorC] = 20;
		}

		else if(SensorValue[my_sensor] >= 55){
			motor[motorA] = 40;
			motor[motorC] = 10;
		}
	}
}
