#pragma config(Sensor, S1,     my_sensor,      sensorLightActive)
#pragma config(Motor,  motorA,          A,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          C,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define kp (50-(-50))/(32.5-(-32.5))
#define offset 47.5
#define tp 25
#define ki 0.08


task main()
{
	float integral=0;
	while(1)
	{
		displayString(3, "Light Value = %d",SensorValue[my_sensor]);
		float error,turn;

		error=SensorValue[my_sensor]-offset;
		integral=(1/3)*integral+error;    //integration
		turn=kp*error+ki*(integral);
		motor[motorA]=tp+turn;
		motor[motorC]=tp-turn;


  }
}
