#pragma config(Sensor, S1,     my_sensor,      sensorLightActive)
#pragma config(Motor,  motorA,          A,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          C,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1)
	{
		if(SensorValue[my_sensor] > 35 && SensorValue[my_sensor] < 45){
			motor[motorA] = 30;
			motor[motorC] = 30;
		}
		else if(SensorValue[my_sensor] >= 35){
			motor[motorA] = 40;
			motor[motorC] = 20;
		}
		else if(SensorValue[my_sensor] <= 45){
			motor[motorA] = 20;
			motor[motorC] = 40;
		}
	}
}
