#pragma config(Sensor, S1,     my_sensor,      sensorLightActive)
#pragma config(Motor,  motorA,          A,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          C,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define kp 1.8
#define offset 45
#define tp 25
#define ki 0.1


task main()
{
	float integral=0,error=0,turn=0,light_value=0;
	while(1)
	{
		displayString(3, "Light Value = %d",SensorValue[my_sensor]);

		light_value=SensorValue[my_sensor];
		error=light_value - offset;
		if(error == 1){
			integral=0;
			}
		else{
			integral=(integral*(3/4)) + error;
		}
		turn=kp*error+(ki*(integral));
		if (turn > 50) {
		    	turn=50;
		}
		if (turn <-50) {
		    	turn=-50;
		}
		motor[motorA]=tp+turn;
		motor[motorC]=tp-turn;


  }
}
