#pragma config(Sensor, S1,     my_sensor,      sensorLightActive)
#pragma config(Motor,  motorA,          A,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          C,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define kp 5
#define offset 47.5
#define tp 50
#define ki 3
#define kd 3

task main()
{
	float integral=0,error=0,turn=0,lastError=0,derivative=0;
	while(1)
	{
		displayString(3, "Light Value = %d",SensorValue[my_sensor]);

		error=SensorValue[my_sensor]-offset;
		integral=(1/3)*integral+error;   //integration gives acceleration to the body when it deviates and this acceleration
		//increases as the deviation increases.but id does not give us the ability to break and that is why our system
		//oscilates if we increase the speed.

		derivative=error-lastError;     //derivation stops the osscilations and gives breaks when the body comes near the zero.
		//and at the same time gives a small amount of acceleration when the deviation increases
		lastError=error;

		turn=kp*error+ki*(integral)+kd*(derivative);  //taqyeem ilmawqif+ilwaqt wa ilmady kan izzay+taqyeemak lilmostaqbal=rad ilfe3l

		motor[motorA]=tp+turn;
		motor[motorC]=tp-turn;


  }
}
