#pragma config(Sensor, S1,     my_sensor,      sensorLightActive)
#pragma config(Motor,  motorA,          A,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          C,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{

	while(1)
	{
		if(SensorValue[my_sensor]<=35){

		//wait1Msec(5000);
			motor[motorA]=0;
		  motor[motorC]=0;
		  wait1Msec(1000);
		  motor[motorA]=30;
		  motor[motorC]=-30;
		  wait1Msec(1000);

		}
		else if(SensorValue[my_sensor]>=45){
			motor[motorA]=30;
			motor[motorC]=30;
	}
  }
}
